name: Check broken links on Saturday

on:
  pull_request:
    branches:
      - master
  schedule:
    - cron:  '10 13 * * SAT'
jobs:
  check-links:
    name: Check broken links
    runs-on: ubuntu-latest
    needs:
      - build-vuepress
    steps:
      - uses: actions/download-artifact@v1
        with:
          name: vuepress-pre-site

      - name: Check links
        uses: chabad360/htmlproofer@master
        with:
          directory: vuepress-site
          arguments: >-
            --assume-extension
            --typhoeus-config '{"timeout": 60}'
            --url-ignore "/www\.consultant\.ru/.*/,/github.com\/.*\/edit\/.*/"

  build-vuepress:
    name: Build VuePress site and generate roadmap tree
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ~/.cache/yarn
          key: ${{ runner.os }}-yarn-${{ hashFiles(format('{0}{1}', github.workspace, '/yarn.lock')) }}
          restore-keys: |
            ${{ runner.os }}-yarn-

      - name: Install js dependencies
        run: yarn install --frozen-lockfile

      - name: Build vuepress site
        run: yarn run site:build

      - name: Upload pre-site to artifact
        uses: actions/upload-artifact@v1
        with:
          name: vuepress-pre-site
          path: tlroadmap/.vuepress/dist

      # - name: Upload trees
      #   uses: actions/upload-artifact@v1
      #   with:
      #     name: trees
      #     path: tlroadmap/.vuepress/trees
