name: Checks

on: [pull_request]

jobs:
  readme-md:
    name: README.md check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Python 3.8
        uses: actions/setup-python@v1
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/requirements.txt

      - name: README check
        run: |
          cd tools
          bash check_readme.sh

  yaspeller:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Spell check
        # problem matching breaks loop when it finds unrelated data, so we use reverse grep to clear output
        run: |
          echo "::add-matcher::.github/problem-matchers/yaspeller.json"
          set -o pipefail; npx yaspeller -c .yaspellerrc.json . 2>&1 >/dev/null | grep -v "\-\-\-\-\-" | grep -v "Typos"

  editor-config:
    name: Editor Config check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Editor Config Check
        # problem matching breaks loop when it finds unrelated data, so we use reverse grep to clear output
        run: |
          echo "::add-matcher::.github/problem-matchers/editor-config.json"
          set -o pipefail; npx eclint check "**/*.md" 2>&1 >/dev/null | grep -v "EditorConfig"
